### ISSUE TITLE
Feed unavailable - 403 Forbidden

### ISSUE THREAD

**Issue by Markbraggins** [britishcycling-oa/opendata#1]
Trying to access the data feed http://api.letsride.co.uk/public/v1/rides which is returning a 403 forbidden error

**Comment by domfennell** [comment]
Hi @Markbraggins, @nickevansuk & I have been liaising with British Cycling to rectify this issue. Should be all sorted soon.

**Comment by ghost** [comment]
Any update on this issue? Thanks

**Comment by domfennell** [comment]
Hi @ben-cuttlefish,

I caught up with British Cycling's developer earlier this week - this is to be worked on by the @openactive-bot team next week. @nickevansuk 

Will keep you up-to-date.

**Comment by benjamindoe** [comment]
Hi, is there any update on the api? @nickevansuk

**Comment by nickevansuk** [comment]
I understand this should be resolved this week or next or so (@sevenpointsix?)

**Comment by nickevansuk** [comment]
It appears that this access issue (403) is now resolved. There are however two issues with the contents of the endpoint (#2 and #3). Closing this issue for now - @sevenpointsix is working on the other two.
