### ISSUE TITLE
Conformance to RPDE specification

### ISSUE THREAD

**Issue by nickevansuk** [britishcycling-oa/opendata#2]
Hi Chris! There's a few minor changes to the Let's Ride feed required bring it in line with the [RPDE specification](https://www.openactive.io/realtime-paged-data-exchange/) as the [original endpoint](https://github.com/openactive/activation/issues/5) was previously.

Note that the below only provides conformance to RPDE, and does not provide conformance to the [modelling specification](https://www.openactive.io/modelling-opportunity-data/) - see the [other issue](https://github.com/openactive/activation/issues/104) for details of that):

1) Use `data` to contain your data inside the item (see example below)
2) Include a "license" (see example below)
3) Include afterId and afterTimestamp parameters in the next URL (and check the [underlying query](https://www.openactive.io/realtime-paged-data-exchange/#sql-query-example-for-timestamp-id))
4) Ensure that deleted items are included and flagged with `"state": "deleted"` (note that `data` must *not* be included for deleted items)
5) Ensure that the feed validates with the [RPDE validator](http://openactive.io/endpoint-validator) 

```
{
  "next": "http://api.letsride.co.uk/public/v1/rides?afterTimestamp=1453931925&afterId=2710",
  "items": [
    {
      "state": "updated",
      "id": 2744,
      "kind": "event",
      "modified": "1970-01-01 01:06:24",
      "data": {
        "title": "Wanstead Return Ride",
        "start_time": "2011-09-04T14:00:00Z",
        "type": "Anyone",
        "suitable_for": "Children aged 8-15;Children aged 11-15;Adults 16+ only",
        "distance": "8.00",
        "estimated_cycling_time": 64,
        "estimated_total_time": 0,
        "city": "Redbridge",
        "location": "Redbridge",
        "difficulty": "",
        "postcode": "EC3N 4AB",
        "start_latitude": "51.50827385",
        "start_longitude": "-0.07627169",
        "description": "After enjoying the central Skyride route why not join LCC for a easy paced guided ride home from Tower Hill to Wanstead, on quiet traffic light routes, in the company of others.",
        "free_spaces": null,
        "max_participants": null
      }
    },
    {
      "state": "deleted",
      "id": 41180,
      "kind": "event",
      "modified": "1970-01-01 01:06:24",
    }
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
```

**Comment by ldodds** [comment]
To add to @nickevansuk comments, the list of items should be specified with an `items` key (as shown in Nick's example) rather than `data`. 

The `data` key should be nested within each feed item and used to store additional data other than the `state`, `id`, `kind` and `modified` values. See Nick's example for a clearer illustration! :)

**Comment by GetTheData** [comment]
Adding to @nickevansuk and @ldodds comments, it would be great if this were updated to conform with the [Realtime Paged Data Exchange spec](https://www.openactive.io/realtime-paged-data-exchange/).

**Comment by sevenpointsix** [comment]
@nickevansuk The updated API endpoint is now ready to test on our UAT/staging server.

This should conform to RDPE specification and also the new modelling specification. See:

http://api.bclr.uat.rroom.net/public/v1/rides

You will need to pass HTTP authentication details to this endpoint. They are:

user: webadmin
password: basketabellthatrings

Let me know if this is all you need in order to verify that the API is now correct? Thanks!

**Comment by nickevansuk** [comment]
Hello @sevenpointsix, great will take a look!

We can't seem to see anything new at http://api.bclr.uat.rroom.net/public/v1/rides, and it doesn't prompt for authentication?

Is this the correct URL?

**Comment by sevenpointsix** [comment]
Hi @nickevansuk . Ah, apologies, this is my fault. We updated the UAT server to launch an interim sprint and I believe this will have temporarily reverted the API. Sorry about that. I'll confirm here as soon as the updated version is definitely there for you to review.

**Comment by nickevansuk** [comment]
Hi @sevenpointsix I have provided feedback on the modelling specification (inside the "data" block) here: https://github.com/britishcycling-oa/opendata/issues/3

Note that this feed still does not conform to the RPDE specification, please see the issue at the top of this page for more information.

**Comment by nickevansuk** [comment]
Looks like we're the with this pending deploy to production! Closing this now.
