### ISSUE TITLE
Unicode value \u0000

### ISSUE THREAD

**Issue by house92** [britishcycling-oa/opendata#5]
It seems that occasionally the null Unicode character \u0000 is coming through in your address field (I assume because of the system which the user that has provided the data is using). This breaks our PostgreSQL database, which means we can't make your data available to end users. Could you let me know whether you'd be able to sanitise your users' input to avoid this sort of problem?

**Comment by sevenpointsix** [comment]
@nickevansuk Do we have a tangible example of this?

**Comment by nickevansuk** [comment]
@house92 - one for you?

**Comment by sevenpointsix** [comment]
@nickevansuk @house92 Do we have an update on this...? Thanks!

**Comment by house92** [comment]
@sevenpointsix This doesn't appear to be an issue anymore

**Comment by nickevansuk** [comment]
Closing as appears to have been resolved
